analytics:
  google:
    anonymize_ip: false
    tracking_id: null
  provider: false
author:
  avatar: null
  bio: 个人简介。
  douban: null
  email: null
  facebook: null
  github: null
  googleplus: null
  linkedin: null
  medium: null
  name: 墨问非名
  npm: null
  telegram: null
  twitter: null
  type: null
  url: null
  weibo: null
  zhihu: null
baseurl: null
chart: true
comments:
  disqus:
    shortname: null
  gitalk:
    admin: null
    clientID: null
    clientSecret: null
    owner: null
    repository: null
  provider: valine
  valine:
    app_id: null
    app_key: null
    meta: null
    placeholder: null
    visitor: null
defaults:
- scope:
    path: ''
    type: posts
  values:
    aside:
      toc: true
    layout: article
    license: true
    pageview: true
    sharing: true
    show_edit_on_github: true
    show_subscribe: true
description: 'Lofter2Hexo迁移支援

  '
excerpt_separator: <!--more-->
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- /docs
- /node_modules
- /screenshots
- /test
- /vendor
highlight_theme: default
highlighter: rouge
lang: zh-Hans
license: CC-BY-NC-4.0
markdown: kramdown
mathjax: true
mathjax_autoNumber: true
mermaid: true
pageview:
  leancloud:
    app_class: null
    app_id: null
    app_key: null
  provider: false
paginate: 8
paginate_path: /page:num
paths:
  archive: null
  home: null
  root: null
  rss: null
permalink: date
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
repository: lofter2hexo/lofter2hexo.github.io
repository_tree: master
search:
  google:
    custom_search_engine_id: null
  provider: default
sharing:
  addthis:
    id: null
  provider: false
sources: null
text_skin: default
timezone: Asia/Shanghai
title: 非名居
toc:
  selectors: null
url: null
